export const CREATE_RECIPE = "CREATE_RECIPE";
export const LOAD_RECIPES_SUCCESS = "LOAD_RECIPES_SUCCESS";
export const LOAD_LEVELS_SUCCESS = "LOAD_LEVELS_SUCCESS";
export const CREATE_RECIPE_SUCCESS = "CREATE_RECIPE_SUCCESS";
export const UPDATE_RECIPE_SUCCESS = "UPDATE_RECIPE_SUCCESS";
